### ISSUE TITLE
The ability to specify style

### ISSUE THREAD

**Issue by Shatur95** [nvim-lua/diagnostic-nvim#30]
Could you add the ability to specify signs colors? It would be nice to have warnings in yellow color, error in red etc.
And I suggest to add the ability to specify different highlighting groups for warnings and errors inside text. For example, let user replace underline with something like this in yellow color for warnings and red for errors:
![изображение](https://user-images.githubusercontent.com/22453358/83901631-c3650580-a763-11ea-96f2-90a74fefbc86.png)

**Comment by haorenW1025** [comment]
I think you can change the highlight of the signs by changing the `texthl`
```vim
call sign_define("LspDiagnosticsErrorSign", {"text" : "E", "texthl" : "LspDiagnosticsError"})
call sign_define("LspDiagnosticsWarningSign", {"text" : "W", "texthl" : "LspDiagnosticsWarning"})
call sign_define("LspDiagnosticInformationSign", {"text" : "I", "texthl" : "LspDiagnosticsInformation"})
call sign_define("LspDiagnosticHintSign", {"text" : "H", "texthl" : "LspDiagnosticsHint"})
```

**Comment by Shatur95** [comment]
Sorry, you are right, I missed it :(
Maybe make them colored by default?..

**Comment by haorenW1025** [comment]
@Shatur95 Hmm I think having them colored by default can lead to other issues, such as overwrite user defined highlight...Personally right now I think `diagnostic-nvim` shouldn't do too much stuff cause it's just an extra layer on top of the built-in LSP.

**Comment by Shatur95** [comment]
Agree, you are right.

What about the ability to change warnings / errors highlighting? It is not possible now, right?

**Comment by haorenW1025** [comment]
@Shatur95 I'll look into it:)

**Comment by Shatur95** [comment]
It would be awesome!

**Comment by Iron-E** [comment]
I'd like to echo @Shatur95's comment. Specifically, these four highlight groups from `coc.nvim` do this task:

* `CocErrorHighlight`
* `CocHintHighlight`
* `CocInfoHighlight`
* `CocWarningHighlight`

I usually `highlight link` them to things like `SpellBad`, `SpellRare`, `SpellLocal`, etc. and it allows me to see the errors more quickly.

Is defining an underline for the errors a feature of the LSP right now? If it isn't, taking this over to neovim/neovim too might not be a bad idea.

**Comment by Iron-E** [comment]
I've done a little digging. It seems there are a few things:

* There is a reference to a highlight group `LspDiagnosticsUnderline` in the code although I can't seem to find another reference to it.
* `vim.lsp.util.buf_diagnostics_underline()` is called although it doesn't do anything.

That said, I was able to make this work: manually setting `LspDiagnosticsUnderline` (example below) and then causing `diagnostic-nvim` to trigger an error message makes the highlight group appear as desired.

```viml
highlight! LspDiagnosticsUnderline guifg=#000000 guibg=#ffffff
```

That should make the text show up to you. You'll have to style it the way you want, however. I'll be adding it to [`nvim-highlite`](https://github.com/Iron-E/nvim-highlite) in just a minute (fair disclosure, I'm the author of that theme).

There's no `:help` reference for `LspDiagnosticsUnderline` in Neovim (that should be done upstream in the `lsp.txt` page) which doesn't help things.

___

Is this what you were looking for, @Shatur95?

**Comment by Shatur95** [comment]
Interesting! Is there a way to distinguish highlight between errors and warnings?

**Comment by Iron-E** [comment]
Not from what I've seen. That might be worth taking up in the Neovim repo as that's where the function comes from.

As for this issue, maybe we can define a highlight by default (if one is not present already) if `g:diagnostics_enable_underline` is set to true?

**Comment by Shatur95** [comment]
> CocErrorHighlight
> CocHintHighlight
> CocInfoHighlight
> CocWarningHighlight


Or just add something like this :)

**Comment by Iron-E** [comment]
I went poking around the neovim/neovim repo and found these highlight groups:

* 'LspDiagnosticsUnderlineError',
* 'LspDiagnosticsUnderlineHint',
* 'LspDiagnosticsUnderlineInformation',
* 'LspDiagnosticsUnderlineWarning',

Gonna try them and report back in a bit, but thought I'd drop them here for now.

**Comment by Shatur95** [comment]
Thank you a lot!
This is just what I need!
