### ISSUE TITLE
Error executing vim.schedule lua callback diagnostic/util.lua:149 Index out of bounds

### ISSUE THREAD

**Issue by ahmedelgabri** [nvim-lua/diagnostic-nvim#36]
I keep getting this error especially when I open a `.lua` file

So this is my setup (and also if I open the file I get these errors) https://github.com/ahmedelgabri/dotfiles/blob/26f32ba6aae362a20095523b180f5f06d74f5bcb/roles/vim/files/.vim/lua/lsp.lua

And the error seems to be coming from this line https://github.com/nvim-lua/diagnostic-nvim/blob/bdef92a8d434329c47077e12373f2f62e82c70cf/lua/diagnostic/util.lua#L149

```
Error executing vim.schedule lua callback: ...ack/minpac/start/diagnostic-nvim/lua/diagnostic/util.lua:149: Index out of bounds
Error executing vim.schedule lua callback: ...ack/minpac/start/diagnostic-nvim/lua/diagnostic/util.lua:149: Index out of bounds
Error executing vim.schedule lua callback: ...ack/minpac/start/diagnostic-nvim/lua/diagnostic/util.lua:149: Index out of bounds
```

Here is a recording of the issue, I only opened the file and moved the cursor up/down.

[![asciicast](https://asciinema.org/a/JvkSSmb9XKiX0V9t1RsIYgbkb.svg)](https://asciinema.org/a/JvkSSmb9XKiX0V9t1RsIYgbkb)

**Comment by gavares** [comment]
I'm seeing the same issue while editing `.scala` files using nvim-lsp. The errors seem to happen very frequently when trying to create new functions or classes.

**Comment by Iron-E** [comment]
If you use `vim-sandwich`, it will happen every time you use one of the `sr` (surround replace) commands. It doesn't happen when using `sa` (surround add) or `sd` (surround delete). If I have some time later today I might try to look at the differences between these mappings.

**Comment by gavares** [comment]
PlugSnapshot output if this is helpful:

```
" Generated by vim-plug
" Sat Jul  4 10:36:03 2020
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ayu-vim'].commit = '0745635'
silent! let g:plugs['completion-nvim'].commit = '81ec73b'
silent! let g:plugs['diagnostic-nvim'].commit = 'bdef92a'
silent! let g:plugs['echodoc.vim'].commit = '4719626'
silent! let g:plugs['falcon'].commit = 'da34685'
silent! let g:plugs['fzf.vim'].commit = '2bf85d2'
silent! let g:plugs['gruvbox'].commit = 'bf2885a'
silent! let g:plugs['nerdcommenter'].commit = 'fade3d4'
silent! let g:plugs['nerdtree'].commit = '6571452'
silent! let g:plugs['nvim-lsp'].commit = '8defde9'
silent! let g:plugs['nvim-metals'].commit = '1138826'
silent! let g:plugs['oceanic-next'].commit = '08158ee'
silent! let g:plugs['vim-airline'].commit = 'ba9b3e1'
silent! let g:plugs['vim-airline-themes'].commit = '04fa4fc'
silent! let g:plugs['vim-better-whitespace'].commit = '8cf4b21'
silent! let g:plugs['vim-devicons'].commit = '1ac5894'
silent! let g:plugs['vim-easymotion'].commit = 'dd7b4b5'
silent! let g:plugs['vim-elixir'].commit = '53c530f'
silent! let g:plugs['vim-fugitive'].commit = '1da7c13'
silent! let g:plugs['vim-nerdtree-syntax-highlight'].commit = 'c838988'
silent! let g:plugs['vim-polyglot'].commit = 'd09a56a'
silent! let g:plugs['vim-signify'].commit = 'c3d450e'
silent! let g:plugs['vim-solarized8'].commit = '5df7666'
silent! let g:plugs['vim-tmux-navigator'].commit = '44ba6fb'
```

**Comment by Iron-E** [comment]
I created a PR that should fix this. Can you try it out and verify?

**Comment by haorenW1025** [comment]
For the virtaul text issue you can open another issue for it.
