### ISSUE TITLE
attempt to index field 'diagnostics_by_buf' (a nil value)

### ISSUE THREAD

**Issue by badranX** [nvim-lua/diagnostic-nvim#42]
I'm only using 

`lua require'nvim_lsp'.pyls.setup{on_attach=require'diagnostic'.on_attach}
`

but I'm getting the following error message:

> Error executing vim.schedule lua callback: ...al/share/nvim/plugged/diagnostic-nvim/lua/diagnostic.lua:75: attempt to index field 'diag
nostics_by_buf' (a nil value)

Almost everything related to LSP stopped working.

**Comment by haorenW1025** [comment]
Try updating neovim to the latest master branch, it should fix that.

**Comment by badranX** [comment]
Sorry, I shouldn't have posted the issue in the first place.
