### ISSUE TITLE
Question: Virtual text styling

### ISSUE THREAD

**Issue by bfulop** [nvim-lua/diagnostic-nvim#43]
Hello @haorenW1025,

Thank you for creating this great plugin, I love it!

I have a question about the _virtual text_ feature: how can one change the text color (`guifg`) of the virtual text?

Sorry to ask it here, I was unable to find any info in it anywhere.

**Comment by haorenW1025** [comment]
I believe you can change it by using these highlight group `LspDiagnosticsError`, `LspDiagnosticsWarning`, `LspDiagnosticsInformation` and `LspDiagnosticsHint`

**Comment by bfulop** [comment]
Perfect, thank you @haorenW1025! Working perfectly. ✅
