### ISSUE TITLE
ALE Integration

### ISSUE THREAD

**Issue by nathunsmitty** [nvim-lua/diagnostic-nvim#52]
[ALE](https://github.com/dense-analysis/ale) is a great plugin for showing linting errors. It also has an API exposed for providing diagnostics from other plugins or tools for it to display (see section 3.2, [`ale-lint-other-sources`](https://github.com/dense-analysis/ale/blob/master/doc/ale.txt))

I've been playing around with integrating diagnostic-nvim with ALE through this API, and have gotten pretty promising results. Would this be a feature that you'd be interested in merging? I'm also happy to split this functionality out into a separate plugin, since ALE duplicates many of the features already provided by diagnostic-nvim.

**Comment by FabioRamatis** [comment]
I really like this features because with ale i can get eslint errors and with diagnostic-nvim the language aware errors
It would be amazing to merge those!

**Comment by nathanmsmith** [comment]
Hey everyone! Given the deprecation of this plugin (#73), I've [created a new small plugin](https://github.com/nathunsmitty/nvim-ale-diagnostic) that works with the new integrated Neovim diagnostic APIs.
